#!/bin/bash
#this is a comment-the first line sets bash as the shell script
export PATH="//anaconda/bin:$PATH"

echo Nellie88 | sudo -S $MYSQL_HOME/bin/mysqld_safe &
cd ~/Documents/Workspace/Projects/LakVyuh/python_scripts/
python lnk_json_reader_all.py 2>&1 | tee log/$(date +%Y%m%d-%H%M%S).txt
